Intro to Tensors

In [2]:
import torch

In [3]:
# create a 0D tensor (scalar) from a Python integer
tensor0d = torch.tensor(1)

# create a 1D tensor (vector) from a Python list
tensor1d = torch.tensor([1, 2, 3])

# create a 2D tensor from a nested Python list
tensor2d = torch.tensor([[1, 2], [3, 4]])

# create a 3D tensor from a nested Python list
tensor3d = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [4]:
# create a 1D tensor (vector) from a Python list
tensor1d = torch.tensor([1, 2, 3])
#Pytorch adopts the defaudlt 64-bit integer data type from Python
print(tensor1d.dtype)

torch.int64


In [5]:
# Tensors from Python float
tensor1d_float = torch.tensor([1.0, 2.0, 3.0])
# Creates tensors with the 32- bit precision by default
print(tensor1d_float.dtype)

torch.float32


A 32-bit floating point number offers sufficient precision for most deep learning tasks, while consuming less memory and computational resources than a 64-bit floating point number.

In [ ]:
# 64-bit int can be converted to 32-bit

In [7]:
to_float = tensor1d.to(torch.float32)
print(to_float.dtype)

torch.float32


In [8]:
tensor2d = torch.tensor([[1, 2, 3],
                         [4, 5, 6]])
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [9]:
#shape a tensor

print(tensor2d.shape)

torch.Size([2, 3])


In [10]:
# The 2 row- 3 column tensor can be reshaped
tensor2d.reshape(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [11]:
# In the same vein, .view can be used to reshape
tensor2d.view(3, 2)


tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [12]:
# .T - fillping it across its diagonal
tensor2d.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [13]:
# Tensors can be multiplied using the .matmul method

tensor2d.matmul(tensor2d.T)

tensor([[14, 32],
        [32, 77]])

In [14]:
# Using the @ operator for the multiplication
tensor2d @ tensor2d.T

tensor([[14, 32],
        [32, 77]])

Models as computation graphs
These are directed graphs that help in expressing and visualizing mathematical expressions. In DL, it lays out the sequence of calculations needed to compute the output of a neural network.

In [15]:
# Implements a forward pass of a simple logistic regression clasifier

import torch.nn.functional as F

y = torch.tensor([1.0])  # true label - expected to be predicted, i.e. actual
x1 = torch.tensor([1.1]) # input feature
w1 = torch.tensor([2.2]) # weight parameter
b = torch.tensor([0.0])  # bias unit

z = x1 * w1 + b          # net input
a = torch.sigmoid(z)     # activation & output - predicted

loss = F.binary_cross_entropy(a, y) #- difference between predicted and actual
print(loss)

tensor(0.0852)


In [16]:
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True) # So that PyTorch internally builds the computation graph
b = torch.tensor([0.0], requires_grad=True)

z = x1 * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

grad_L_w1 = grad(loss, w1, retain_graph=True) # To retain the gradient, calling the grad function
grad_L_b = grad(loss, b, retain_graph=True)

In [17]:
print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)


In [ ]:
# PyTorch has high level tools for  calculating the gradient

In [18]:
loss.backward()

print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])
